# Generated by Django 6.1.1 on 2026-09-28 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief summary of the incident', max_length=200)),
                ('description', models.TextField(help_text='Detailed narrative of what occurred')),
                ('date_time', models.DateTimeField(help_text='When the incident occurred', verbose_name='Date & Time of Incident')),
                ('location', models.CharField(help_text='Airport code, airspace waypoint, or geographic coordinates', max_length=200)),
                ('aircraft_type', models.CharField(help_text='e.g., Boeing 737-800, Airbus A320, Cessna 172', max_length=100)),
                ('category', models.CharField(choices=[('bird_strike', 'Bird Strike'), ('technical_fault', 'Technical Fault'), ('weather', 'Weather'), ('human_error', 'Human Error'), ('other', 'Other')], default='other', help_text='Primary classification of the incident', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Impact severity level', max_length=20)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_review', 'Under Review'), ('investigating', 'Investigating'), ('closed', 'Closed')], default='reported', help_text='Current investigation status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reported At')),
                ('reported_by', models.ForeignKey(help_text='User who logged this incident', on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aviation Incident',
                'verbose_name_plural': 'Aviation Incidents',
                'ordering': ['-date_time', '-created_at'],
            },
        ),
    ]
